image:
  file: .gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
  onOpen: open-preview
- port: 9001
  onOpen: ignore
- port: 15672
  onOpen: ignore
  visibility: public
vscode:
  extensions:
    - TabNine.tabnine-vscode@3.4.14
    - felixfbecker.php-debug@1.16.0
github:
  prebuilds:
    master: true
    branches: true
tasks:
  - openMode: tab-after
    name: "Services"
